permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: xcation
  email: yyy541501@gmail.com
  link: http://xcation.github.io/
  weibo: http://weibo.com/idreamnet
  github: http://github.com/xcation

# 站点信息
title: 我的博客 
description: 我的博客
url: http://xcation.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://xcation.github.io/images/gavatar.jpg
favicon: http://xcation.github.io/images/favicon.ico


# disqus 设置
disqus:
  shortname: xcation-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
